
application: fredsa-bliss2
version: one
runtime: python27
api_version: 1
threadsafe: false
vm: true

manual_scaling:
  instances: 1

vm_settings:
  machine_type: n1-standard-1
  apt_get_install: vim


handlers:
- url: /bliss2
  script: bliss2.app
  secure: always

- url: /app
  static_dir: app
  secure: always

- url: /
  static_files: app/index.html
  upload: app/index.html
  secure: always

- url: /.*
  script: main.APPLICATION
  secure: always
